package swagger

import (
	"github.com/gorilla/mux"
	_ "github.com/hessegg/nikto-explorer/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/hessegg/nikto-explorer/types"
	"github.com/hessegg/nikto-explorer/types/config"
	httpSwagger "github.com/swaggo/http-swagger"
)

type Handler struct {
	ctx    types.Context
	config config.ApiConfig
}

var _ types.Handler = &Handler{}

func NewHandler(ctx types.Context, config config.ApiConfig) *Handler {
	return &Handler{
		ctx:    ctx,
		config: config,
	}
}

func (h *Handler) Run() {}

func (h *Handler) swaggerConfig() config.SwaggerConfig {
	return h.config.Handler.Swagger
}

func (h *Handler) RegisterRoute(router *mux.Router) *mux.Router {
	if h.swaggerConfig().Enable {
		router.PathPrefix("/swagger/").Handler(httpSwagger.Handler())
		h.ctx.Logger().Debug("RegisterRoute", "/swagger/")
	}
	return router
}
